on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Check Docs Links
        if: always()
        uses: lycheeverse/lychee-action@v2
        with:
          args: -r 10 docs/articles/**/*.md docs/articles/**/*.yml
      - name: Check Blog Links
        uses: lycheeverse/lychee-action@v2
        if: always()
        with:
          args: -r 10 web/_posts/**/*.md
      - name: Check Web Data Links
        uses: lycheeverse/lychee-action@v2
        if: always()
        with:
          args: -r 10 web/_data/**/*.json
      - name: Check Changelog Links
        uses: lycheeverse/lychee-action@v2
        if: always()
        with:
          args: -r 10 Changelog.md
