pipeline {
  agent any
  stages {
    stage('Pull') {
      when { 
        branch 'main' 
      }
      steps {
        sh '''cd /var/www/tinylifegame
              git fetch
              git checkout ${GIT_COMMIT} -f'''
      }
    }
  }
}